apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: task-pv-claim

spec:
  storageClassName: standard
  accessModes:
    - ReadWriteOnce # access mode of pvc should same as access mode of pv
  resources:
    requests:
      storage: 500Mi # requesting 500 mb memory from pv
