# metadata
# spec
#status
apiVersion: v1
kind: Pod
metadata:
  name: tomcat-pod
  labels:
    app: tomcat
spec:
  containers:
    - image: tomcat:9.0
      name: tomcat-container
      ports:
        - containerPort: 8080
